
link_with 'Travis-Demo', 'Travis-DemoTests'

pod 'ErrorKit/Default', :path => '../'
pod 'ErrorKit/Accounts', :path => '../'
pod 'ErrorKit/AdMob', :path => '../'
pod 'ErrorKit/AFNetworking_v1', :path => '../'
pod 'ErrorKit/AVFoundation', :path => '../'
pod 'ErrorKit/Core', :path => '../'
pod 'ErrorKit/CoreData', :path => '../'
pod 'ErrorKit/CoreLocation', :path => '../'
pod 'ErrorKit/FacebookSDK_v2', :path => '../'
pod 'ErrorKit/HTTP', :path => '../'
pod 'ErrorKit/JSONKit', :path => '../'
pod 'ErrorKit/JSONValues', :path => '../'
pod 'ErrorKit/MapKit', :path => '../'
pod 'ErrorKit/MessageUI', :path => '../'
pod 'ErrorKit/NSException', :path => '../'
pod 'ErrorKit/Parse', :path => '../'
pod 'ErrorKit/Security', :path => '../'
pod 'ErrorKit/StoreKit', :path => '../'
pod 'ErrorKit/TransitionKit', :path => '../'
pod 'ErrorKit/iAD', :path => '../'
pod 'ErrorKit/UIKit', :path => '../'
pod 'ErrorKit/VeriJSON', :path => '../'

pod 'AFIncrementalStore', "~> 0.5.1"

